#!/bin/sh
set -e
case "$1" in
    remove|upgrade|deconfigure)
        if [ -d /run/systemd/system ]; then
            systemctl stop label-printer.service || true
            [ "$1" = remove ] && systemctl disable label-printer.service >/dev/null 2>&1 || true
        fi
        ;;
esac
exit 0
