"""mDNS announcement through Avahi.

Avahi watches /etc/avahi/services, so announcing is writing a service file and
withdrawing is deleting it. The file is generated from the settings, so it can
never disagree with what the server reports on /info.
"""

from pathlib import Path
from xml.sax.saxutils import escape

from . import API_VERSION
from .config import LABEL_DPI, Settings

SERVICE_TYPE = "_labelprinter._tcp"
SERVICE_FILE = Path("/etc/avahi/services/label-printer.service")


def service_xml(settings: Settings) -> str:
    txt = {
        "v": str(API_VERSION),
        "path": "/info",
        "model": settings.model,
        "label": settings.label,
        "dpi": str(LABEL_DPI),
    }
    records = "\n".join(f"    <txt-record>{escape(k)}={escape(v)}</txt-record>" for k, v in txt.items())
    return f"""<?xml version="1.0" standalone='no'?>
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<!-- Generated by label-printer from its settings; removed when the service stops. -->
<service-group>
  <name replace-wildcards="yes">Label printer on %h</name>
  <service>
    <type>{SERVICE_TYPE}</type>
    <port>{settings.port}</port>
{records}
  </service>
</service-group>
"""


def install(settings: Settings, path: Path = SERVICE_FILE) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(service_xml(settings), encoding="utf-8")
    path.chmod(0o644)


def remove(path: Path = SERVICE_FILE) -> None:
    path.unlink(missing_ok=True)
